config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  root to: 'static_pages#home'

  get 'sobre-o-projeto' => 'static_pages#about'
  get 'politica-de-reembolso' => 'static_pages#refunds'
  get 'perguntas-frequentes' => 'static_pages#faq'
  
  get 'palestrantes/:slug' => 'speakers#show'

  get 'upgrade' => 'upgrade_requests#new', as: :new_upgrade_request

  get 'agreement_term' => 'static_pages#agreement_term'

  get 'select' => 'static_pages#select'

  resources :upgrade_requests, only: [:create]

  resources :users, only: :update

  namespace :basis_plena do
    resources :videos, only: [:index, :show]
  end

  namespace :event do
    resources :lectures, only: [:index, :show]
  end

  namespace :admin do
    resources :upgrade_requests do
      member do
        patch 'mark_as_paid'
      end
    end

    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  scope :saturday, -> { where(day: 'saturday') }
  scope :sunday, -> { where(day: 'sunday') }
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  after_create :create_slug

  scope :international, -> { where(international: true) }
  scope :national, -> { where.not(international: true) }

  def create_slug
    update(slug: name.parameterize)
  end
end

app/models/upgrade_request.rb
class UpgradeRequest < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :e_ticket, presence: true

  enum upgrade_to: [:gold_1_to_gold_2, :gold_1_to_vip_1, :gold_1_to_vip_2, :gold_2_to_vip_1, :gold_2_to_vip_2]

  enum status: [:pending, :paid]

  after_create :set_default_status

  def set_default_status
    update(status: 'pending')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  self.per_page = 7
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/admin/upgrade_requests_controller.rb
module Admin
  class UpgradeRequestsController < AdminController
    def index
      @upgrade_requests = UpgradeRequest.all
    end

    def mark_as_paid
      @upgrade_request = UpgradeRequest.find(params[:id])

      respond_to do |format|
        @upgrade_request.update(status: 'paid')

        format.html { redirect_to admin_upgrade_requests_path,
                                  notice: 'Solicitação marcada como paga.' }
      end
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      @users = User.all.order(name: :asc)

      if params[:q] and not(params[:q].blank?)
        @users = @users.where("name ILIKE ? OR email ILIKE ? OR e_ticket ILIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
      end

      @users = @users.paginate(page: params[:page])

      respond_to do |format|
        format.html
        format.js
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_admin

  protected

  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :agreement_term

  def after_sign_in_path_for(_user)
    if current_user.admin?
      admin_upgrade_requests_path
    else
      select_path
    end
  end

  def agreement_term
    if user_signed_in? and not(current_user.admin?)
      if controller_path == 'basis_plena/videos' or controller_path == 'event/lectures'
        @user = current_user

        unless current_user.term
          render 'static_pages/agreement_term', layout: 'agreement'
        end
      end
    end
  end
end

app/controllers/basis_plena/videos_controller.rb
module BasisPlena
  class VideosController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @videos = Video.all.order(number: :asc)
    end

    def show
      @video = Video.find(params[:id])
    end
  end
end

app/controllers/event/lectures_controller.rb
module Event
  class LecturesController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @lectures = Lecture.all.order(number: :asc)
    end

    def show
      @lecture = Lecture.find(params[:id])
    end
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def show
    @speaker = Speaker.find_by_slug(params[:slug])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'agreement', only: :agreement_term

  before_action :authenticate_user!, only: :select

  def home
    @speakers = Speaker.national.shuffle
    @international_speakers = Speaker.international.order(position: :asc)
  end

  def about
  end

  def refunds
  end

  def faq
  end

  def select
  end

  def agreement_term
    @user = current_user
  end
end

app/controllers/upgrade_requests_controller.rb
class UpgradeRequestsController < ApplicationController
  before_action :set_upgrade_to

  def new
    @upgrade_request = UpgradeRequest.new  
  end

  def create
    params[:upgrade_request][:upgrade_to] = params[:upgrade_request][:upgrade_to].to_i

    @upgrade_request = UpgradeRequest.new(upgrade_request_params)

    respond_to do |format|
      if @upgrade_request.save
        format.html { redirect_to new_upgrade_request_path,
                      notice: 'Sua solicitação foi recebida com sucesso! Em breve entraremos em contato.' }
      else
        format.html { render 'new' }
      end
    end
  end

  def upgrade_request_params
    params.require(:upgrade_request).permit(:name, :email, :e_ticket, :upgrade_to)
  end

  def set_upgrade_to
    @upgrade_to = [["Gold 1 para Gold 2", 0], ["Gold 1 para VIP 1", 1], ["Gold 1 para VIP 2", 2], ["Gold 2 para VIP 1", 3], ["Gold 2 para VIP 2", 4]]
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'devise'
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to basis_plena_videos_path }
      else
        render 'static_pages/agreement_term', layout: 'agreement'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/upgrade_requests/_upgrade_request.html.erb
<tr>
  <td>
    <% if upgrade_request.status == 'pending' %>
      <div class="badge badge-info">pendente</div>
    <% elsif upgrade_request.status == 'paid' %>
      <div class="badge badge-success">pago</div>
    <% end %>
  </td>

  <td><%= upgrade_request.created_at.strftime('%d/%m/%Y') %></td>
  <td><%= upgrade_request.name %></td>
  <td><%= upgrade_request.email %></td>
  <td><%= upgrade_request.e_ticket %></td>

  <td>
    <% if upgrade_request.upgrade_to == 'gold_1_to_gold_2' %>
      Gold 1 para Gold 2
    <% elsif upgrade_request.upgrade_to == 'gold_1_to_vip_1' %>
      Gold 1 para VIP 1
    <% elsif upgrade_request.upgrade_to == 'gold_1_to_vip_2' %>
      Gold 1 para VIP 2
    <% elsif upgrade_request.upgrade_to == 'gold_2_to_vip_1' %>
      Gold 2 para VIP 1
    <% elsif upgrade_request.upgrade_to == 'gold_2_to_vip_2' %>
      Gold 2 para VIP 2
    <% end %>
  </td>

  <td>
    <div class="btn-group">
      <button type="button" class="btn btn-warning btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      </button>
      <div class="dropdown-menu">
        <%= link_to 'Marcar como paga', mark_as_paid_admin_upgrade_request_path(upgrade_request),
                                        method: :patch,
                                        data: { confirm: 'Você tem certeza?' },
                                        class: 'dropdown-item' %>
      </div>
    </div>
  </td>
</tr>

app/views/admin/upgrade_requests/index.html.erb
<div class="admin-module">
  <div class="admin-title">
    <div class="container">
      <h2>Solicitações de upgrade</h2>
    </div>
  </div>

  <% if notice %>
    <div class="alert alert-success">
      <div class="container">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <div class="container admin-content">
    <% if @upgrade_requests.empty? %>
      <div class="alert alert-info">
        Ainda não há solicitações de upgrade de categoria.
      </div>
    <% else %>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>Status</th>
            <th>Data</th>
            <th>Nome</th>
            <th>Email</th>
            <th>E-ticket</th>
            <th>De/Para</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @upgrade_requests %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/users/_user.html.erb
<% unless user.admin %>
  <tr>
    <td>
      <% if user.term %>
        <%= fa_icon 'check', class: 'text-success' %>
      <% end %>
    </td>
    
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.e_ticket %></td>
    <td><%= user.created_at.strftime('%d/%m/%y') %></td>
  </tr>
<% end %>

app/views/admin/users/index.html.erb
<div class="admin-module pb-5">
  <div class="admin-title">
    <div class="container">
      <h2>Participantes</h2>
    </div>
  </div>

  <% if notice %>
    <div class="alert alert-success">
      <div class="container">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <div class="container admin-content">
    <% if @users.empty? %>
      <div class="alert alert-info">
        Ainda não há participantes.
      </div>
    <% else %>
      <form action="/admin/users" class="user-search" data-remote="true">
        <input class="form-control" type="search" name="q" placeholder="Pesquise por nome, email ou e-ticket">
      </form>

      <table class="table users mt-4">
        <thead class="thead-light">
          <tr>
            <th>Termo</th>
            <th>Nome</th>
            <th>Email</th>
            <th>E-ticket</th>
            <th>Criado em</th>
          </tr>
        </thead>

        <tbody>
          <%= render @users %>
        </tbody>
      </table>

      <div class="d-flex justify-content-center pt-4">
        <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.js.erb
$('.users tbody').html('<%= j (render @users) %>');

$('.pagination').html("<%= j(will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/basis_plena/videos/_cta.html.erb
<section class="cta">
  <div class="container d-flex">
    <div class="text">
      O Basis Plena, é um grupo multidisciplinar que atua através de uma plataforma de cursos onde você poderá desenvolver as áreas de: nutrição, mente, físico e conhecimento para que você tenha mais qualidade de vida.
      <br><br>
      Não importa se o caso é emagrecimento ou a sua preciosa saúde, estamos aqui para te proporcionar equilíbrio de vida e cuidado pleno. 
      <br><br>

      <strong>BASIS PLENA: O SER HUMANO LEVADO A SÉRIO!</strong>
    </div>

    <%= image_tag 'logo-basis-plena@2x.png', class: 'ml-auto align-self-center' %>
  </div>
</section>

<section class="discount">
  <div class="container d-flex flex-wrap wrap-reverse">
    <div class="div">
      <div class="text">
        <strong>TEMOS MAIS UMA SURPRESA PARA VOCÊ:</strong><br><br>

        Todos os inscritos além das aulas que vocês acabaram de assistir tem também desconto exclusivo (exceto em maratonas) na plataforma de cursos do Basis Plena. Use o código: <strong>ALIMENTE20</strong> e aproveite todo o conteúdo disponível! 
      </div>

      <div class="link">
        <div class="d-md-none d-block">
          <%= link_to 'ADQUIRA NOSSOS CURSOS', 'http://www.basisplena.com.br', class: 'btn btn-warning btn-block', target: '_blank' %>
        </div>

        <div class="d-md-block d-none">
          <%= link_to 'ADQUIRA NOSSOS CURSOS', 'http://www.basisplena.com.br', class: 'btn btn-warning btn-lg', target: '_blank' %>
        </div>
      </div>
    </div>

    <div class="coupon">
      ALIMENTE20
    </div>
  </div>
</section>

app/views/basis_plena/videos/index.html.erb
<div class="basis-plena">
  <div class="header">
    <div class="container h-100 d-flex justify-content-center">
      <div class="title align-self-center">
        BASIS PLENA
      </div>
    </div>
  </div>

  <% if notice %>
    <div class="alert alert-success">
      <div class="container">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <div class="container videos">
    <div class="sub-title">
      Seja bem-vindo a série de aulas exclusivas para os participantes do Evento Alimente 2019.
    </div>

    <div class="table-responsive">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>Nº</th>
            <th>Título</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @videos.each do |video| %>
            <tr>
              <td>
                <strong><%= video.number %></strong>
              </td>
              <td><%= video.title %></td>
              <td align="right"><%= link_to 'ASSISTIR VÍDEO', basis_plena_video_path(video), class: 'btn btn-warning btn-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= render 'cta' %>
</div>

app/views/basis_plena/videos/show.html.erb
<div class="basis-plena">
  <div class="header">
    <div class="container h-100 d-flex justify-content-center">
      <div class="title align-self-center">
        BASIS PLENA
      </div>
    </div>
  </div>

  <div class="container video">
    <div class="title">
      <%= @video.number %>. <%= @video.title %>
    </div>

    <iframe src="https://www.youtube.com/embed/<%= @video.video_url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <div class="description">
      <%= @video.description.html_safe %>
    </div>

    <%= link_to 'VOLTAR À LISTA DE VÍDEOS', :back, class: 'btn btn-outline-info' %>
  </div>

  <%= render 'cta' %>
</div>

app/views/event/lectures/index.html.erb
<div class="basis-plena">
  <div class="header">
    <div class="container h-100 d-flex justify-content-center">
      <div class="title align-self-center">
        EVENTO ONLINE
      </div>
    </div>
  </div>

  <% if notice %>
    <div class="alert alert-success">
      <div class="container">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <div class="container">
    <div class="lectures">
      <div class="row pt-2 pb-4">
        <div class="col-md-6 col-6 col-sm-6">
          <div class="day-of-week saturday -active">
            <h2>SÁBADO</h2>
          </div>
        </div>

        <div class="col-md-6 col-6 col-sm-6">
          <div class="day-of-week sunday">
            <h2>DOMINGO</h2>
          </div>
        </div>
      </div>

      <div class="saturday-lectures pt-4">
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>Título</th>
                <th>Palestrante</th>
                <th>Assistir</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @lectures.saturday.each do |lecture| %>
                <tr>
                  <td>
                    <strong><%= lecture.name %></strong>
                  </td>
                  <td><%= lecture.speaker %></td>
                  <td align="right"><%= link_to 'ASSISTIR PALESTRA', event_lecture_path(lecture), class: 'btn btn-warning btn-sm' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="sunday-lectures d-none pt-4">
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>Título</th>
                <th>Palestrante</th>
                <th>Assistir</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @lectures.sunday.each do |lecture| %>
                <tr>
                  <td>
                    <strong><%= lecture.name %></strong>
                  </td>
                  <td><%= lecture.speaker %></td>
                  <td align="right"><%= link_to 'ASSISTIR PALESTRA', event_lecture_path(lecture), class: 'btn btn-warning btn-sm' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/event/lectures/show.html.erb
<div class="basis-plena">
  <div class="header">
    <div class="container h-100 d-flex justify-content-center">
      <div class="title align-self-center">
        EVENTO ONLINE
      </div>
    </div>
  </div>

  <div class="container video">
    <div class="title" style="line-height: 1.5">
      <%= @lecture.name %> - <%= @lecture.speaker %>
    </div>

    <iframe src="https://www.youtube.com/embed/<%= @lecture.video_url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <%= link_to 'VOLTAR À LISTA DE PALESTRAS', :back, class: 'btn btn-outline-info mt-4' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="title">O EVENTO</div>

        <ul class="list">
          <li class="list-item"><a href="/">Edição 2019</a></li>
          <li class="list-item d-none"><a href="#">Edições anteriores</a></li>
          <li class="list-item"><a href="/perguntas-frequentes">Perguntas frequentes</a></li>
          <li class="list-item"><a href="/politica-de-reembolso">Reembolsos e transferências</a></li>
        </ul>
      </div>

      <div class="col-md-4">
        <div class="title">O PROJETO ALIMENTE</div>

        <ul class="list">
          <li class="list-item"><a href="/sobre-o-projeto">Sobre o projeto</a></li>
          <li class="list-item"><a href="/sobre-o-projeto#trabalhe-conosco">Trabalhe conosco</a></li>
        </ul>
      </div>

      <div class="col-md-4">
        <div class="title">PAGAMENTO</div>

        <%= image_tag 'formas-de-pagamento@2x.png', class: 'payment-methods' %>

        <div class="title pt-4 pb-2">MÍDIAS SOCIAIS</div>

        <a href="http://instagram.com/eventoalimente" target="_blank" class="social"><%= fa_icon 'instagram' %></a>
        <span>&nbsp;</span>
        <a href="http://facebook.com/eventoalimente" target="_blank" class="social"><%= fa_icon 'facebook' %></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar <%= 'app-navbar' if action_name == 'home' or controller_path == 'users/sessions' or controller_path == 'basis_plena/videos' or controller_path == 'event/lectures' %> <%= 'project-navbar' if action_name == 'about' or action_name == 'faq' or action_name == 'refunds' or controller_name == 'speakers' or controller_name == 'upgrade_requests' %> navbar-expand-lg navbar-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag 'alimente-logo@2x.png' %>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <a class="nav-item nav-link" href="/sobre-o-projeto">O PROJETO</a>
        <a class="nav-item nav-link" href="/#palestrantes">PALESTRANTES</a>
        <a class="nav-item nav-link d-none" href="#">PROGRAMAÇÃO</a>
        <a class="nav-item nav-link" href="/perguntas-frequentes">FAQ</a>
        <a class="nav-item nav-link" href="/basis_plena/videos">BASIS PLENA</a>
        <a class="nav-item nav-link" href="/event/lectures">EVENTO ONLINE</a>

        <% if user_signed_in? %>
          <%= link_to 'SAIR', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>  
        <% end %>
      </div>

      <%= link_to 'ASSISTA ONLINE', "https://www.sympla.com.br/evento-alimente-2019__322894", target: '_blank', class: 'btn btn-warning' %>
    </div>
  </div>
</nav>

app/views/layouts/_ticket_banner.html.erb
<div class="ticket-banner">
  <div class="container d-flex align-items-center justify-content-between">
    <div class="watch">
      <a href="https://www.sympla.com.br/evento-alimente-2019__322894" target="_blank">
        <h1 class="title m-0">ASSISTA ONLINE</h1>
      </a>
    </div>

    <div class="buy">
      <h4 class="title">JÁ DISPONÍVEL</h4>

      <a href="https://www.sympla.com.br/evento-alimente-2019__322894" class="btn btn-success btn-lg mt-3" target="_blank">COMPRAR AGORA</a>
    </div>

    <div class="access">
      <h4 class="title">FOI AO EVENTO?</h4>

      <%= link_to 'ACESSE AGORA', new_user_session_path, class: 'btn btn-lg mt-3 btn-outline-success' %>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administração - EVENTO ALIMENTE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  </head>
  <body>  
    <%= render 'layouts/admin/navbar' %>
    
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light admin-navbar">
  <div class="container">
    <a class="navbar-brand" href="#">ADMINISTRAÇÃO</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to 'Solicitações de upgrade', admin_upgrade_requests_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Basis Plena', basis_plena_videos_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Participantes', admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'VER SITE', root_path, class: 'btn btn-warning' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/agreement.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EVENTO ALIMENTE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  </head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login - EVENTO ALIMENTE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  </head>
  <body class="devise">
    <%= render 'layouts/navbar' %>

    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/home/_words_box.html.erb
<section class="words-box">
  <div class="d-none d-md-block">
    <%= image_tag 'words-box.png', class: 'image-responsive w-100' %>
  </div>

  <div class="d-block d-md-none">
    <%= image_tag 'words-box-mobile.png', class: 'image-responsive w-100' %>
  </div>
</section>

app/views/static_pages/select.html.erb
<div class="select">
  <div class="container h-100">
    <div class="h-100">
      <div class="d-none d-md-flex align-items-center justify-content-between h-100">
        <%= link_to basis_plena_videos_path do %>
          <div class="basis-plena">
            Basis Plena
          </div>
        <% end %>
        
        <%= link_to event_lectures_path do %>
          <div class="online-event">
            Evento Online
          </div>
        <% end %>
      </div>

      <div class="d-block d-md-none">
        <%= link_to basis_plena_videos_path do %>
          <div class="basis-plena-mobile">
            Basis Plena
          </div>
        <% end %>
        
        <%= link_to event_lectures_path do %>
          <div class="online-event-mobile">
            Evento Online
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>